# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - ApolloQA/*
pr:
 - master

pool:
  vmImage: 'windows-latest'

variables:
- name: SourceDir
  value: '$(Build.SourcesDirectory)/ApolloQA'

stages:

- stage: QA
  displayName: 'QA'
  condition: or(eq('${{ variables.environmentLabel}}', ''), eq('${{ variables.environmentLabel}}', 'QA'))
  jobs: 
  - job: RunAutomatedTest
    displayName: 'Run Automated Tests'
    steps:
    - template: 'azure-run-steps.yml'
      parameters: 
        environmentLabel: 'QA'
        KEY_VAULT: 'https://xbibaoazckv-qa.vault.azure.net/'

- stage: QAInt
  displayName: 'QAInt'
  condition: or(eq('${{ variables.environmentLabel}}', ''), eq('${{ variables.environmentLabel}}', 'QAInt'))

  jobs: 
  - template: 'azure-aproval.yml'
    parameters: 
      environment: automation_qaint

  - job: RunAutomatedTest
    displayName: 'Run Automated Tests'
    steps:
    - template: 'azure-run-steps.yml'
      parameters: 
        environmentLabel: 'QAInt'
        KEY_VAULT: ''https://xbibaoazckv2-qa2.vault.azure.net/

- stage: QA2
  displayName: 'QA2'
  condition: or(eq('${{ variables.environmentLabel}}', ''), eq('${{ variables.environmentLabel}}', 'QA2'))

  jobs: 
  - template: 'azure-aproval.yml'
    parameters: 
      environment: automation_qa2

  - job: RunAutomatedTest
    displayName: 'Run Automated Tests'
    steps:
    - template: 'azure-run-steps.yml'
      parameters: 
        environmentLabel: 'QA2'

- stage: UAT
  displayName: 'UAT'
  condition: or(eq('${{ variables.environmentLabel}}', ''), eq('${{ variables.environmentLabel}}', 'UAT'))
  jobs: 
  - template: 'azure-aproval.yml'
    parameters: 
     environment: 'automation_uat' 
       
  
  - job: RunAutomatedTest
    displayName: 'Run Automated Tests'
    steps:
    - template: 'azure-run-steps.yml'
      parameters: 
        environmentLabel: 'UAT'