# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - ApolloQA/*

pool:
  vmImage: 'windows-latest'

variables:
- name: Browser
  value: Chrome


steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/ApolloQA_SpecFlow.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\ApolloQA_SpecFlow.sln'
    restoreNugetPackages: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:Browser = "chrome"
      Write-Host "Current Browser Value is $env:Browser"
- task: VSTest@2
  displayName: 'Running a Smoke Test'
  continueOnError: true
  timeoutInMinutes: 10
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\ApolloQA_SpecFlow.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'SmokeTest'
