// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Referred.RetailWholesaleStoresInclFoodStores_R
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_PetAndPetSupplyStore_RFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_PetAndPetSupplyStore_R.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Referred/RetailWholesaleStoresInclFoodStores_R", "WC_PetAndPetSupplyStore_R", @"Keyword: Pet and Pet Supply Store 
Ineligible quote: Experience Mod not within the allowable limits
Yes I have Employee
Number of employee : 11
Business Operation: I Lease a Space From Others
ZIP Code: 10122
Included Officer: 1
Business started year : Started 12 years ago
Business Structured: LLC
EechAccidentPolicyEachEmpLimit: 100,000/500,000/100,000  
Payment Option: 15% Down + 9 Monthly Installments 
XMOD: 1.5
153 W 29th St, New York, NY 10001", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_PetAndPetSupplyStore_R")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Referred.RetailWholesaleStoresInclFoodStores_R.WC_PetAndPetSupplyStore_RFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Pet And Pet Supply Store gets referred because exp mod not within the allowabl" +
            "e limits")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_PetAndPetSupplyStore_R")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Retail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Referred")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NY")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        public void WCPetAndPetSupplyStoreGetsReferredBecauseExpModNotWithinTheAllowableLimits()
        {
            string[] tagsOfScenario = new string[] {
                    "Retail",
                    "WC",
                    "Referred",
                    "NY",
                    "Regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Pet And Pet Supply Store gets referred because exp mod not within the allowabl" +
                    "e limits", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3010 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table3010.AddRow(new string[] {
                            "Pet and Pet Supply Store",
                            "11",
                            "I Lease a Space From Others",
                            "",
                            "10001",
                            "WC"});
#line 18
 testRunner.Given("user starts a quote with:", ((string)(null)), table3010, "Given ");
#line hidden
#line 21
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3011 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table3011.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table3011.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 10 years or more ago"});
                table3011.AddRow(new string[] {
                            "How is your business structured?",
                            "Limited Liability Co. (LLC)"});
                table3011.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "100000"});
                table3011.AddRow(new string[] {
                            "Business",
                            "Pet Store Xmod not in limits"});
                table3011.AddRow(new string[] {
                            "Address",
                            "153 W 29th St;New York"});
                table3011.AddRow(new string[] {
                            "Contact First Name",
                            "TestF"});
                table3011.AddRow(new string[] {
                            "Contact Last Name",
                            "TestL"});
                table3011.AddRow(new string[] {
                            "Email",
                            "Test@Test123.com"});
                table3011.AddRow(new string[] {
                            "Phone",
                            "1231231321"});
                table3011.AddRow(new string[] {
                            "Business website",
                            "test.com"});
#line 22
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table3011, "Then ");
#line hidden
#line 35
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3012 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table3012.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "1"});
                table3012.AddRow(new string[] {
                            "How many owners/officers do you want to cover with this policy?",
                            "1"});
#line 36
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table3012, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3013 = new TechTalk.SpecFlow.Table(new string[] {
                            "First Name",
                            "Last Name",
                            "W2 Payroll",
                            "Annual Payroll"});
                table3013.AddRow(new string[] {
                            "TestF",
                            "TestL",
                            "Yes",
                            "40000"});
#line 40
 testRunner.Then("user handles the WC Covered OO with these values:", ((string)(null)), table3013, "Then ");
#line hidden
#line 43
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3014 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table3014.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table3014.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "yes"});
                table3014.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
                table3014.AddRow(new string[] {
                            "Does your business have a state-issued experience modification factor (XMOD)?",
                            "yes"});
                table3014.AddRow(new string[] {
                            "Enter the value for experience modification factor:",
                            "1.5"});
#line 44
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table3014, "Then ");
#line hidden
#line 51
 testRunner.Then("user begins the WC AI page setting the FEIN with value 63-1212123", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
 testRunner.Then("wc user handles 1 covered oo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
 testRunner.Then("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3015 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table3015.AddRow(new string[] {
                            "Business name",
                            "Test Multi State Referal"});
                table3015.AddRow(new string[] {
                            "Contact first name",
                            "TestF"});
                table3015.AddRow(new string[] {
                            "Contact last name",
                            "TestL"});
                table3015.AddRow(new string[] {
                            "Email",
                            "TestCert@Plan.com"});
                table3015.AddRow(new string[] {
                            "Phone",
                            "(123) 123-1321"});
                table3015.AddRow(new string[] {
                            "Business website",
                            "www.TestPartnerCert.com"});
#line 54
 testRunner.When("user fills out the WC refer page with these values:", ((string)(null)), table3015, "When ");
#line hidden
#line 62
 testRunner.Then("user verifies the refer thank you page appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
