// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Referred.AutoServicesAndDealers_R
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_Ridesharing_RFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_Ridesharing_R.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Referred/AutoServicesAndDealers_R", "WC_Ridesharing_R", "Reason for referral: answered yes to \"Do you lease or rent out any vehicles to an" +
                    "y non-employees?\"", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_Ridesharing_R")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Referred.AutoServicesAndDealers_R.WC_Ridesharing_RFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Ridesharing gets referred due to renting vehicles to any non-employees")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_Ridesharing_R")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Referred")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NJ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Transportation")]
        public void WCRidesharingGetsReferredDueToRentingVehiclesToAnyNon_Employees()
        {
            string[] tagsOfScenario = new string[] {
                    "Referred",
                    "Regression",
                    "NJ",
                    "WC",
                    "Transportation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Ridesharing gets referred due to renting vehicles to any non-employees", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2938 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table2938.AddRow(new string[] {
                            "Ridesharing",
                            "2",
                            "I Run My Business From Property I Own",
                            "Vehicles",
                            "08046",
                            "WC"});
#line 7
 testRunner.Given("user starts a quote with:", ((string)(null)), table2938, "Given ");
#line hidden
#line 10
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2939 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2939.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table2939.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 10 years or more ago"});
                table2939.AddRow(new string[] {
                            "How is your business structured?",
                            "Corporation"});
                table2939.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "50000"});
                table2939.AddRow(new string[] {
                            "Do any employees do any maintenance, repair, or service on motor vehicles?",
                            "no"});
                table2939.AddRow(new string[] {
                            "Do any employees only do general office work and rarely travel?",
                            "no"});
                table2939.AddRow(new string[] {
                            "Business",
                            "RideSharing"});
                table2939.AddRow(new string[] {
                            "Address",
                            "77 Evergreen Dr;Willingboro"});
                table2939.AddRow(new string[] {
                            "Contact First Name",
                            "TestF"});
                table2939.AddRow(new string[] {
                            "Contact Last Name",
                            "TestL"});
                table2939.AddRow(new string[] {
                            "Email",
                            "Test@Test123.com"});
                table2939.AddRow(new string[] {
                            "Phone",
                            "1231233212"});
                table2939.AddRow(new string[] {
                            "Business website",
                            "test.com"});
#line 11
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table2939, "Then ");
#line hidden
#line 26
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2940 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2940.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "1"});
#line 27
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table2940, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2941 = new TechTalk.SpecFlow.Table(new string[] {
                            "First Name",
                            "Last Name",
                            "W2 Payroll",
                            "Annual Payroll",
                            "Job Duty"});
                table2941.AddRow(new string[] {
                            "OneF",
                            "OneL",
                            "yes",
                            "50000",
                            "Driver or Mechanic"});
#line 30
 testRunner.Then("user handles the WC Covered OO with these values:", ((string)(null)), table2941, "Then ");
#line hidden
#line 33
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2942 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2942.AddRow(new string[] {
                            "How many vehicles do you own that are operated by employees?",
                            "1"});
                table2942.AddRow(new string[] {
                            "Do you lease or rent out any vehicles to any non-employees?",
                            "yes"});
                table2942.AddRow(new string[] {
                            "How many vehicles do you lease or rent out to non-employees?",
                            "1"});
                table2942.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table2942.AddRow(new string[] {
                            "Do you pay any drivers via 1099 that use their own vehicle?",
                            "no"});
                table2942.AddRow(new string[] {
                            "Do you review MVRs for all employees with a driving exposure?",
                            "Yes at the time of hire and annually"});
                table2942.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "yes"});
                table2942.AddRow(new string[] {
                            "Do the business owner(s) of this business have a combined majority ownership in a" +
                                "ny other transportation business?",
                            "no"});
                table2942.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
#line 34
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table2942, "Then ");
#line hidden
#line 45
 testRunner.Then("user begins the WC AI page setting the FEIN with value 23-1516789", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
 testRunner.Then("wc user handles 1 covered oo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
 testRunner.Then("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2943 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2943.AddRow(new string[] {
                            "Business name",
                            "RideSharing"});
                table2943.AddRow(new string[] {
                            "Contact first name",
                            "TestF"});
                table2943.AddRow(new string[] {
                            "Contact last name",
                            "TestL"});
                table2943.AddRow(new string[] {
                            "Email",
                            "Test@Test123.com"});
                table2943.AddRow(new string[] {
                            "Phone",
                            "1231233212"});
                table2943.AddRow(new string[] {
                            "Business website",
                            "www.TestPartnerCert.com"});
#line 48
 testRunner.When("user fills out the WC refer page with these values:", ((string)(null)), table2943, "When ");
#line hidden
#line 56
 testRunner.Then("user verifies the refer thank you page appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
