# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
trigger: none

pr: none

schedules:
  - cron: "0 8 * * *" # Run every day at 3AM EST (8AM UTC)
  

pool:
  vmImage: 'windows-latest'

parameters:
  - name: TargetEnvironment
    displayName: Environment
    type: string
    default: QA
    values:
    - QA
    - QA2
    - QAInt
    - Dev1
    - Dev2
    - Dev3
    - Dev4

stages:

- stage: Trigger
  displayName: 'Trigger'
  jobs: 
  - job: Trigger
    displayName: 'Trigger Test Plans'
    steps:
    - task: PowerShell@2
      displayName: 'Run trigger script'
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/Pipeline.Forms/triggerTestPlanRun.ps1
      env:
        PlanId: 96142 
        TargetEnvironment: ${{ parameters.TargetEnvironment }}
        TargetReleaseId: 5 
        ACCESS_TOKEN: $(System.AccessToken)
        ADO_ORG: biberk
        ADO_PROJ: biBERK 


