# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
trigger: none


pr: none

schedules:
  - cron: "0 5 * * *" # Run every day at 1AM EST (8AM UTC)
    displayName: "Daily overnight test run"
    always: true  # Run this pipeline even if there aren't source code changes (otherwise it may, for example, deploy to TESTING, then skip QA in the next morning)
    branches:
      include:
      - master

pool:
  vmImage: 'windows-latest'

parameters:
  - name: TargetEnvironment
    displayName: Environment
    type: string
    default: QA
    values:
    - QA
    - QA2
    - QAInt
    - Dev1
    - Dev2
    - Dev3
    - Dev4

stages:

- stage: Trigger
  displayName: 'Trigger'
  jobs: 
  - job: Trigger
    displayName: 'Trigger Test Plans'
    steps:
    - task: PowerShell@2
      displayName: 'Run trigger script'
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/Pipeline.Forms/triggerTestPlanRun.ps1
      env:
        PlanId: 96142 
        TargetEnvironment: ${{ parameters.TargetEnvironment }}
        TargetReleaseId: 5 
        BEARER_TOKEN: $(System.AccessToken)
        ADO_ORG: biberk
        ADO_PROJ: biBERK 


