// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Issued.ServiceIndustries_I
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_ArbitrationOrMediation_IFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_ArbitrationOrMediation_I.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Issued/ServiceIndustries_I", "WC_ArbitrationOrMediation_I", "WC Issued FF For Arbitration or Mediation  in Indiana (IN)", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_ArbitrationOrMediation_I")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Issued.ServiceIndustries_I.WC_ArbitrationOrMediation_IFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Arbitration Or Mediation Issued In Indiana")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_ArbitrationOrMediation_I")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Issued")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("IN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("YourServices")]
        public void WCArbitrationOrMediationIssuedInIndiana()
        {
            string[] tagsOfScenario = new string[] {
                    "Issued",
                    "Regression",
                    "IN",
                    "WC",
                    "YourServices"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Arbitration Or Mediation Issued In Indiana", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2634 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Client Home",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table2634.AddRow(new string[] {
                            "Arbitration or Mediation",
                            "3",
                            "I Run My Business Out of My Home",
                            "No",
                            "",
                            "47167",
                            "WC"});
#line 7
 testRunner.Given("user starts a quote with:", ((string)(null)), table2634, "Given ");
#line hidden
#line 10
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2635 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2635.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table2635.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 7 years ago"});
                table2635.AddRow(new string[] {
                            "How is your business structured?",
                            "Limited Liability Co. (LLC)"});
                table2635.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "70000"});
                table2635.AddRow(new string[] {
                            "Business",
                            "Test Business"});
                table2635.AddRow(new string[] {
                            "Address",
                            "8000 N OLD FORESTRY RD;Salem"});
                table2635.AddRow(new string[] {
                            "Contact First Name",
                            "TestF"});
                table2635.AddRow(new string[] {
                            "Contact Last Name",
                            "TestL"});
                table2635.AddRow(new string[] {
                            "Email",
                            "Test@Test123.com"});
                table2635.AddRow(new string[] {
                            "Phone",
                            "2551234587"});
                table2635.AddRow(new string[] {
                            "Business website",
                            "test.com"});
#line 11
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table2635, "Then ");
#line hidden
#line 24
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2636 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2636.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "2"});
                table2636.AddRow(new string[] {
                            "How many owners/officers do you want to cover with this policy?",
                            "2"});
#line 25
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table2636, "Then ");
#line hidden
#line 29
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
 testRunner.Then("user verifies the appearance of the WC Your Services Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2637 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2637.AddRow(new string[] {
                            "What percentage of work involves Bankruptcy, Corporate, Intellectual Property, or" +
                                " Real Estate law?",
                            "15"});
                table2637.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table2637.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
#line 31
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table2637, "Then ");
#line hidden
#line 36
 testRunner.Then("user verifies the appearance of the WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 37
    testRunner.Then("user clicks continue from WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
    testRunner.Then("user verifies the WC your quote page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2638 = new TechTalk.SpecFlow.Table(new string[] {
                            "Customization",
                            "Value"});
                table2638.AddRow(new string[] {
                            "ELL - Each Accident / Total Policy / Each Employee",
                            "100,000/500,000/100,000"});
#line 39
 testRunner.When("user selects a plus plan quote with the following customizations from the WC your" +
                        " quote page:", ((string)(null)), table2638, "When ");
#line hidden
#line 42
 testRunner.Then("user begins the WC AI page setting the FEIN with value 23-1326965", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
 testRunner.And("wc user handles 2 covered oo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
 testRunner.And("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2639 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2639.AddRow(new string[] {
                            "CC Name",
                            "Funky Chicken-cheese"});
                table2639.AddRow(new string[] {
                            "CC Number",
                            "4111111111111111"});
                table2639.AddRow(new string[] {
                            "CC Expiration Month",
                            "11"});
                table2639.AddRow(new string[] {
                            "CC Expiration Year",
                            "25"});
                table2639.AddRow(new string[] {
                            "Autopay",
                            "N/A"});
                table2639.AddRow(new string[] {
                            "First Name",
                            "TestF"});
                table2639.AddRow(new string[] {
                            "Last Name",
                            "TestL"});
                table2639.AddRow(new string[] {
                            "Email",
                            "TestFTestL@Test123.com"});
                table2639.AddRow(new string[] {
                            "Phone",
                            "7777777777"});
                table2639.AddRow(new string[] {
                            "Same Billing Info?",
                            "Yes"});
#line 45
 testRunner.Then("user fills out the WC purchase page with these values:", ((string)(null)), table2639, "Then ");
#line hidden
#line 57
 testRunner.Then("user verifies the WC how would you rate our service modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
 testRunner.And("user verifies the WC thank you page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
 testRunner.And("user verifies that these LOBs are recommended: PL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
