// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Issued.ServiceIndustries_I
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_CommercialCleaningServices_LessThan50Percent_Residential_IFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_CommercialCleaningServices_LessThan50Percent_Residentia_l.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Issued/ServiceIndustries_I", "WC_CommercialCleaningServices_LessThan50Percent_Residential_I", "Issuing a WC Commercial Cleaning Services: Less than 50% Residential Policy in Co" +
                    "nnecticut", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_CommercialCleaningServices_LessThan50Percent_Residential_I")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Issued.ServiceIndustries_I.WC_CommercialCleaningServices_LessThan50Percent_Residential_IFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Commercial Cleaning Services: Less than 50% Residential issued policy in CT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_CommercialCleaningServices_LessThan50Percent_Residential_I")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Service")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Issued")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("CT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("YourServices")]
        public void WCCommercialCleaningServicesLessThan50ResidentialIssuedPolicyInCT()
        {
            string[] tagsOfScenario = new string[] {
                    "Service",
                    "WC",
                    "Issued",
                    "CT",
                    "Regression",
                    "YourServices"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Commercial Cleaning Services: Less than 50% Residential issued policy in CT", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2691 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table2691.AddRow(new string[] {
                            "Commercial Cleaning Services: Less than 50% Residential",
                            "13",
                            "I Lease a Space From Others",
                            "",
                            "26554",
                            "WC"});
#line 6
 testRunner.Given("user starts a quote with:", ((string)(null)), table2691, "Given ");
#line hidden
#line 9
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2692 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2692.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table2692.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 9 years ago"});
                table2692.AddRow(new string[] {
                            "How is your business structured?",
                            "Limited Liability Co. (LLC)"});
                table2692.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "57000"});
                table2692.AddRow(new string[] {
                            "Are there any employees that do not do any cleaning or maintenance work?",
                            "No"});
                table2692.AddRow(new string[] {
                            "Do you use any subcontractors or pay any workers using IRS Form 1099?",
                            "no"});
                table2692.AddRow(new string[] {
                            "Business",
                            "Connecticut Commercial Cleaning Services"});
                table2692.AddRow(new string[] {
                            "Address",
                            "164 Country Estates;Fairmont"});
                table2692.AddRow(new string[] {
                            "Fill Contact",
                            ""});
#line 10
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table2692, "Then ");
#line hidden
#line 21
 testRunner.And("user verifies the Wage Calculator page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
 testRunner.And("user clicks continue from the Wage Calculator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2693 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2693.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "4"});
                table2693.AddRow(new string[] {
                            "How many owners/officers do you want to cover with this policy?",
                            "2"});
                table2693.AddRow(new string[] {
                            "Are there any included owners/officers that do not do any cleaning or maintenance" +
                                " work?",
                            "No"});
#line 24
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table2693, "Then ");
#line hidden
#line 29
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2694 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2694.AddRow(new string[] {
                            "What percentage of work done is water damage, fire damage, or mold restoration?",
                            "10"});
                table2694.AddRow(new string[] {
                            "Do you do any construction related work such as carpentry, drywall, or demolition" +
                                "?",
                            "no"});
                table2694.AddRow(new string[] {
                            "Do you ever transport six or more workers in the same vehicle?",
                            "no"});
                table2694.AddRow(new string[] {
                            "Do you clean any chimneys by crawling inside or climbing on roofs to access them?" +
                                "",
                            "no"});
                table2694.AddRow(new string[] {
                            "Do you clean any exterior windows above ground level?",
                            "no"});
                table2694.AddRow(new string[] {
                            "Do you offer any bulk removal services such as furniture, mattresses, or large ap" +
                                "pliances?",
                            "no"});
                table2694.AddRow(new string[] {
                            "What percentage of work done is residential cleaning?",
                            "10"});
                table2694.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table2694.AddRow(new string[] {
                            "Do you do biological hazard clean up?",
                            "no"});
                table2694.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "yes"});
                table2694.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
                table2694.AddRow(new string[] {
                            "Federal Employer Identification Number (FEIN)",
                            "23-1965495"});
#line 30
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table2694, "Then ");
#line hidden
#line 44
 testRunner.Then("user verifies the appearance of the WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
    testRunner.Then("user clicks continue from WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
    testRunner.Then("user verifies the WC your quote page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2695 = new TechTalk.SpecFlow.Table(new string[] {
                            "Customization",
                            "Value"});
                table2695.AddRow(new string[] {
                            "ELL - Each Accident / Total Policy / Each Employee",
                            "100,000/500,000/100,000"});
#line 47
 testRunner.When("user selects a Plus plan quote with the following customizations from the WC your" +
                        " quote page:", ((string)(null)), table2695, "When ");
#line hidden
#line 50
 testRunner.Then("user begins the WC AI page having the FEIN with value 23-1326965", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2696 = new TechTalk.SpecFlow.Table(new string[] {
                            "Set Name"});
                table2696.AddRow(new string[] {
                            "Rivera Scott"});
                table2696.AddRow(new string[] {
                            "Theresa Lark"});
#line 51
 testRunner.Then("wc user handles 2 excluded oo with these values:", ((string)(null)), table2696, "Then ");
#line hidden
#line 55
 testRunner.Then("wc user handles 2 covered oo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
 testRunner.Then("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2697 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2697.AddRow(new string[] {
                            "Payment Option",
                            "One Pay Plan"});
                table2697.AddRow(new string[] {
                            "CC Name",
                            "Test"});
                table2697.AddRow(new string[] {
                            "CC Number",
                            "4111111111111111"});
                table2697.AddRow(new string[] {
                            "CC Expiration Month",
                            "11"});
                table2697.AddRow(new string[] {
                            "CC Expiration Year",
                            "25"});
                table2697.AddRow(new string[] {
                            "Autopay",
                            "N/A"});
                table2697.AddRow(new string[] {
                            "First Name",
                            "TestF"});
                table2697.AddRow(new string[] {
                            "Last Name",
                            "TestL"});
                table2697.AddRow(new string[] {
                            "Email",
                            "TestFTestL@Test123.com"});
                table2697.AddRow(new string[] {
                            "Phone",
                            "7777777777"});
                table2697.AddRow(new string[] {
                            "Same Billing Info?",
                            "Yes"});
#line 57
 testRunner.Then("user fills out the WC purchase page with these values:", ((string)(null)), table2697, "Then ");
#line hidden
#line 70
 testRunner.Then("user verifies the WC how would you rate our service modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
 testRunner.Then("user verifies the WC thank you page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
