// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Issued.ServiceIndustries_I
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_HairStylist_IFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_HairStylist_I.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Issued/ServiceIndustries_I", "WC_HairStylist_I", "Specifications found in US 98710, Should add the certificate of insurance verific" +
                    "ation steps later on.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_HairStylist_I")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Issued.ServiceIndustries_I.WC_HairStylist_IFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Hair Stylist creates issued policy for Illinois")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_HairStylist_I")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Staging")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Service")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("IL")]
        public void WCHairStylistCreatesIssuedPolicyForIllinois()
        {
            string[] tagsOfScenario = new string[] {
                    "Staging",
                    "Regression",
                    "Service",
                    "WC",
                    "IL"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Hair Stylist creates issued policy for Illinois", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2750 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table2750.AddRow(new string[] {
                            "Hair Stylist",
                            "3",
                            "I Lease a Space From Others",
                            "",
                            "60101",
                            "WC"});
#line 7
 testRunner.Given("user starts a quote with:", ((string)(null)), table2750, "Given ");
#line hidden
#line 10
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2751 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2751.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table2751.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 10 years or more ago"});
                table2751.AddRow(new string[] {
                            "How is your business structured?",
                            "Corporation"});
                table2751.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "120,000"});
                table2751.AddRow(new string[] {
                            "Business",
                            "Test WC;Test DBA"});
                table2751.AddRow(new string[] {
                            "Address",
                            "233 N Mill Rd;Addison"});
                table2751.AddRow(new string[] {
                            "Email",
                            "John.Taggart@biberk.com"});
                table2751.AddRow(new string[] {
                            "Phone",
                            "123-123-1321"});
                table2751.AddRow(new string[] {
                            "Contact First Name",
                            "TestF"});
                table2751.AddRow(new string[] {
                            "Contact Last Name",
                            "TestL"});
#line 11
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table2751, "Then ");
#line hidden
#line 23
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2752 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2752.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "1"});
                table2752.AddRow(new string[] {
                            "How many owners/officers do you want to cover with this policy?",
                            "0"});
#line 24
 testRunner.And("user handles the WC OO kickoff questions with these values:", ((string)(null)), table2752, "And ");
#line hidden
#line 28
 testRunner.And("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2753 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2753.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table2753.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "yes"});
                table2753.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
#line 29
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table2753, "Then ");
#line hidden
#line 34
 testRunner.Then("user verifies the appearance of the WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
 testRunner.Then("user clicks continue from WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2754 = new TechTalk.SpecFlow.Table(new string[] {
                            "Customization",
                            "Value"});
                table2754.AddRow(new string[] {
                            "N/A",
                            "N/A"});
#line 36
 testRunner.When("user selects a standard single-bundle plan quote with the following customization" +
                        "s from the WC your quote page:", ((string)(null)), table2754, "When ");
#line hidden
#line 39
 testRunner.Then("user begins the WC AI page setting the FEIN with value 12-1212123", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2755 = new TechTalk.SpecFlow.Table(new string[] {
                            "Set Name"});
                table2755.AddRow(new string[] {
                            "TestF TestL"});
#line 40
 testRunner.Then("wc user handles 1 excluded oo with these values:", ((string)(null)), table2755, "Then ");
#line hidden
#line 43
 testRunner.Then("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2756 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2756.AddRow(new string[] {
                            "Payment Option",
                            "One Pay Plan"});
                table2756.AddRow(new string[] {
                            "CC Name",
                            "Hair Cutter"});
                table2756.AddRow(new string[] {
                            "CC Number",
                            "4111111111111111"});
                table2756.AddRow(new string[] {
                            "CC Expiration Month",
                            "11"});
                table2756.AddRow(new string[] {
                            "CC Expiration Year",
                            "25"});
                table2756.AddRow(new string[] {
                            "Autopay",
                            "Yes"});
                table2756.AddRow(new string[] {
                            "First Name",
                            "TestF"});
                table2756.AddRow(new string[] {
                            "Last Name",
                            "TestL"});
                table2756.AddRow(new string[] {
                            "Email",
                            "TestFTestL@Test123.com"});
                table2756.AddRow(new string[] {
                            "Phone",
                            "7777777777"});
                table2756.AddRow(new string[] {
                            "Same Billing Info?",
                            "Yes"});
#line 44
 testRunner.Then("user fills out the WC purchase page with these values:", ((string)(null)), table2756, "Then ");
#line hidden
#line 57
 testRunner.Then("user verifies the WC how would you rate our service modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
 testRunner.Then("user verifies the WC thank you page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
 testRunner.Then("user verifies that these LOBs are recommended: PL,BOP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
