// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Issued.RetailWholesaleStoresInclFoodStores_I
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_BuildingMaterialsDealer_IFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_BuildingMaterialsDealer_I.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Issued/RetailWholesaleStoresInclFoodStores_I", "WC_BuildingMaterialsDealer_I", "Issuing Building Materials Dealer policy in Montana.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_BuildingMaterialsDealer_I")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Issued.RetailWholesaleStoresInclFoodStores_I.WC_BuildingMaterialsDealer_IFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Building Materials Dealer issued policy in MT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_BuildingMaterialsDealer_I")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Retail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Issued")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("MT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("YourServices")]
        public void WCBuildingMaterialsDealerIssuedPolicyInMT()
        {
            string[] tagsOfScenario = new string[] {
                    "Retail",
                    "WC",
                    "Issued",
                    "MT",
                    "Regression",
                    "YourServices"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Building Materials Dealer issued policy in MT", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2486 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table2486.AddRow(new string[] {
                            "Building Materials Dealer",
                            "5",
                            "I Lease a Space From Others",
                            "",
                            "59901",
                            "WC"});
#line 7
 testRunner.Given("user starts a quote with:", ((string)(null)), table2486, "Given ");
#line hidden
#line 10
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2487 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2487.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table2487.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 2 years ago"});
                table2487.AddRow(new string[] {
                            "How is your business structured?",
                            "Corporation"});
                table2487.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "80000"});
                table2487.AddRow(new string[] {
                            "Business",
                            "Montana Building Materials"});
                table2487.AddRow(new string[] {
                            "Address",
                            "1004 6th Ave W;Kalispell"});
                table2487.AddRow(new string[] {
                            "Contact First Name",
                            "TestF"});
                table2487.AddRow(new string[] {
                            "Contact Last Name",
                            "TestL"});
                table2487.AddRow(new string[] {
                            "Email",
                            "Test@Test123.com"});
                table2487.AddRow(new string[] {
                            "Phone",
                            "1231231321"});
                table2487.AddRow(new string[] {
                            "Business website",
                            "test.com"});
#line 11
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table2487, "Then ");
#line hidden
#line 24
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2488 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2488.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "1"});
                table2488.AddRow(new string[] {
                            "How many owners/officers do you want to cover with this policy?",
                            "0"});
#line 25
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table2488, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2489 = new TechTalk.SpecFlow.Table(new string[] {
                            "First Name",
                            "Last Name"});
                table2489.AddRow(new string[] {
                            "TestFN",
                            "TestLN"});
#line 29
 testRunner.Then("user handles the WC Excluded OO with these values:", ((string)(null)), table2489, "Then ");
#line hidden
#line 32
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2490 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2490.AddRow(new string[] {
                            "Do you operate any concrete mixing trucks?",
                            "no"});
                table2490.AddRow(new string[] {
                            "What percentage of your overall sales involve delivery?",
                            "10"});
                table2490.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table2490.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "no"});
                table2490.AddRow(new string[] {
                            "When was your last policy in effect?",
                            "Never no prior insurance"});
                table2490.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
#line 33
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table2490, "Then ");
#line hidden
#line 41
 testRunner.Then("user verifies the appearance of the WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
    testRunner.Then("user clicks continue from WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
    testRunner.Then("user verifies the WC your quote page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2491 = new TechTalk.SpecFlow.Table(new string[] {
                            "Customization",
                            "Value"});
                table2491.AddRow(new string[] {
                            "N/A",
                            "N/A"});
#line 44
 testRunner.When("user selects a Standard single-bundle plan quote with the following customization" +
                        "s from the WC your quote page:", ((string)(null)), table2491, "When ");
#line hidden
#line 47
 testRunner.Then("user begins the WC AI page setting the FEIN with value 23-7277824", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
 testRunner.Then("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2492 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2492.AddRow(new string[] {
                            "Payment Option",
                            "One Pay Plan"});
                table2492.AddRow(new string[] {
                            "CC Name",
                            "Test"});
                table2492.AddRow(new string[] {
                            "CC Number",
                            "4111111111111111"});
                table2492.AddRow(new string[] {
                            "CC Expiration Month",
                            "11"});
                table2492.AddRow(new string[] {
                            "CC Expiration Year",
                            "25"});
                table2492.AddRow(new string[] {
                            "Autopay",
                            "Yes"});
                table2492.AddRow(new string[] {
                            "First Name",
                            "TestF"});
                table2492.AddRow(new string[] {
                            "Last Name",
                            "TestL"});
                table2492.AddRow(new string[] {
                            "Email",
                            "TestFTestL@Test.com"});
                table2492.AddRow(new string[] {
                            "Phone",
                            "7777777777"});
                table2492.AddRow(new string[] {
                            "Same Billing Info?",
                            "Yes"});
#line 49
 testRunner.Then("user fills out the WC purchase page with these values:", ((string)(null)), table2492, "Then ");
#line hidden
#line 62
 testRunner.Then("user verifies the WC how would you rate our service modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
 testRunner.Then("user verifies the WC thank you page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
