// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Issued.TransportationAndWarehousing_I
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_Freight_Securement_No_Transport_NE_IFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_Freight_Securement_No_Transport_NE_I.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Issued/TransportationAndWarehousing_I", "WC_Freight_Securement_No_Transport_NE_I", "Zip code: 68516\r\nIssued Policy on WC Freight Securement No transport\r\nScenario fo" +
                    "r Third party transport and half of business goods done by own business", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_Freight_Securement_No_Transport_NE_I")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Issued.TransportationAndWarehousing_I.WC_Freight_Securement_No_Transport_NE_IFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Freight Securement No Transport creates issued policy in Nebraska")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_Freight_Securement_No_Transport_NE_I")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("NE")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("YourServices")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Transportation")]
        public void WCFreightSecurementNoTransportCreatesIssuedPolicyInNebraska()
        {
            string[] tagsOfScenario = new string[] {
                    "NE",
                    "Regression",
                    "YourServices",
                    "WC",
                    "Transportation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Freight Securement No Transport creates issued policy in Nebraska", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2897 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table2897.AddRow(new string[] {
                            "Freight Securement: No Transport",
                            "2",
                            "I Work at a Job Site",
                            "",
                            "68516",
                            "WC"});
#line 9
 testRunner.Given("user starts a quote with:", ((string)(null)), table2897, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2898 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2898.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table2898.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 10 years or more ago"});
                table2898.AddRow(new string[] {
                            "How is your business structured?",
                            "Partnership"});
                table2898.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "50,000"});
                table2898.AddRow(new string[] {
                            "Do any employees only do general office work and rarely travel?",
                            "no"});
                table2898.AddRow(new string[] {
                            "Do you provide any staffing services?",
                            "no"});
                table2898.AddRow(new string[] {
                            "Business",
                            "Shadaloo"});
                table2898.AddRow(new string[] {
                            "Address",
                            "1823 Test Rd;Lincoln"});
                table2898.AddRow(new string[] {
                            "Fill Contact",
                            ""});
#line 12
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table2898, "Then ");
#line hidden
#line 23
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2899 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2899.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "2"});
                table2899.AddRow(new string[] {
                            "How many owners/officers do you want to cover with this policy?",
                            "1"});
#line 24
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table2899, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2900 = new TechTalk.SpecFlow.Table(new string[] {
                            "First Name",
                            "Last Name",
                            "Job Duty"});
                table2900.AddRow(new string[] {
                            "Vega",
                            "Bison",
                            "Driver or Mechanic"});
#line 28
 testRunner.Then("user handles the WC Covered OO with these values:", ((string)(null)), table2900, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2901 = new TechTalk.SpecFlow.Table(new string[] {
                            "First Name",
                            "Last Name"});
                table2901.AddRow(new string[] {
                            "Ken",
                            "Masters"});
#line 31
 testRunner.Then("user handles the WC Excluded OO with these values:", ((string)(null)), table2901, "Then ");
#line hidden
#line 34
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2902 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table2902.AddRow(new string[] {
                            "Is your business in charge of getting any goods to their final destination?",
                            "Yes - we may hire 3rd party transport"});
                table2902.AddRow(new string[] {
                            "How much goods transportation is directly done by your business?",
                            "Half or more"});
                table2902.AddRow(new string[] {
                            "Do you load or unload any goods?",
                            "no"});
                table2902.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table2902.AddRow(new string[] {
                            "Do you transport any hazardous materials?",
                            "no"});
                table2902.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "yes"});
                table2902.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
                table2902.AddRow(new string[] {
                            "Federal Employer Identification Number (FEIN)",
                            "23-7177659"});
#line 35
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table2902, "Then ");
#line hidden
#line 45
 testRunner.Then("user verifies the appearance of the WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
    testRunner.Then("user clicks continue from WC Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
    testRunner.Then("user verifies the WC your quote page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2903 = new TechTalk.SpecFlow.Table(new string[] {
                            "Customization",
                            "Value"});
                table2903.AddRow(new string[] {
                            "ELL - Each Accident / Total Policy / Each Employee",
                            "100,000/500,000/100,000"});
#line 48
 testRunner.When("user selects a standard multi-bundle plan quote with the following customizations" +
                        " from the WC your quote page:", ((string)(null)), table2903, "When ");
#line hidden
#line 51
 testRunner.Then("user continues on from the WC Additional Information page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table2904 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2904.AddRow(new string[] {
                            "Payment Option",
                            "One Pay Plan"});
                table2904.AddRow(new string[] {
                            "CC Name",
                            "Funky Chicken-cheese"});
                table2904.AddRow(new string[] {
                            "CC Number",
                            "4111111111111111"});
                table2904.AddRow(new string[] {
                            "CC Expiration Month",
                            "11"});
                table2904.AddRow(new string[] {
                            "CC Expiration Year",
                            "25"});
                table2904.AddRow(new string[] {
                            "Autopay",
                            "No"});
                table2904.AddRow(new string[] {
                            "First Name",
                            "Funky"});
                table2904.AddRow(new string[] {
                            "Last Name",
                            "Kong"});
                table2904.AddRow(new string[] {
                            "Email",
                            "FunkyKong@Cheese.com"});
                table2904.AddRow(new string[] {
                            "Phone",
                            "7777777777"});
                table2904.AddRow(new string[] {
                            "Same Billing Info?",
                            "Yes"});
#line 52
 testRunner.Then("user fills out the WC purchase page with these values:", ((string)(null)), table2904, "Then ");
#line hidden
#line 65
 testRunner.Then("user verifies the WC how would you rate our service modal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
 testRunner.Then("user verifies the WC thank you page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
