// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApolloQAAutomation.Features.WorkmansComp.Declined.HospitalityAndEntertainmentRecreation_D
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WC_MusicianBand_DFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WC_MusicianBand_D.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Workman\'s Comp/Declined/HospitalityAndEntertainmentRecreation_D", "WC_MusicianBand_D", @"Ineligible Quote for the 
Keyword: Pawn shop
Reason: DeclineReason: want insurance to cover volunteers
Employee option: 2
ZIP code: 07601
Business Structured: Partnership
Business Operation: I Lease a Space From Others  
Business started year : Started 8 years ago", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WC_MusicianBand_D")))
            {
                global::ApolloQAAutomation.Features.WorkmansComp.Declined.HospitalityAndEntertainmentRecreation_D.WC_MusicianBand_DFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("WC Musician: Band declined because want insurance to cover volunteers")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WC_MusicianBand_D")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Hospitality")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Declined")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SC")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Regression")]
        public void WCMusicianBandDeclinedBecauseWantInsuranceToCoverVolunteers()
        {
            string[] tagsOfScenario = new string[] {
                    "WC",
                    "Hospitality",
                    "Declined",
                    "SC",
                    "Regression"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("WC Musician: Band declined because want insurance to cover volunteers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1909 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table1909.AddRow(new string[] {
                            "Musician: Band",
                            "2",
                            "I Lease a Space From Others",
                            "",
                            "07106",
                            "WC"});
#line 14
 testRunner.Given("user starts a quote with:", ((string)(null)), table1909, "Given ");
#line hidden
#line 17
 testRunner.Then("user verifies the appearance of the WC About You Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1910 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1910.AddRow(new string[] {
                            "When do you want your policy to start?",
                            ""});
                table1910.AddRow(new string[] {
                            "When did you start your business?",
                            "Started 8 years ago"});
                table1910.AddRow(new string[] {
                            "How is your business structured?",
                            "Corporation"});
                table1910.AddRow(new string[] {
                            "What is the total annual payroll for W-2 employees? (exclude business owners/offi" +
                                "cers)",
                            "200000"});
                table1910.AddRow(new string[] {
                            "Are there any actors, entertainers, or musicians on staff?",
                            "No"});
                table1910.AddRow(new string[] {
                            "Do you make any payments to workers using IRS Form 1099?",
                            "No"});
                table1910.AddRow(new string[] {
                            "Business",
                            "Musician, Band"});
                table1910.AddRow(new string[] {
                            "Address",
                            "2 MONTROSE ST;Newark"});
                table1910.AddRow(new string[] {
                            "State",
                            "NJ"});
                table1910.AddRow(new string[] {
                            "Zip Code",
                            "07106"});
                table1910.AddRow(new string[] {
                            "Contact First Name",
                            "Musician"});
                table1910.AddRow(new string[] {
                            "Contact Last Name",
                            "Band"});
                table1910.AddRow(new string[] {
                            "Email",
                            "test@test123.com"});
                table1910.AddRow(new string[] {
                            "Phone",
                            "1212631654"});
                table1910.AddRow(new string[] {
                            "Business website",
                            "www.GoldandPawn.com"});
#line 18
 testRunner.Then("user fills out the WC About You page with these values:", ((string)(null)), table1910, "Then ");
#line hidden
#line 35
 testRunner.Then("user verifies the appearance of the WC Owners and Officers Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1911 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1911.AddRow(new string[] {
                            "How many owners/officers does your business have?",
                            "1"});
#line 36
 testRunner.Then("user handles the WC OO kickoff questions with these values:", ((string)(null)), table1911, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1912 = new TechTalk.SpecFlow.Table(new string[] {
                            "First Name",
                            "Last Name",
                            "W2 payroll",
                            "Annual Payroll",
                            "Job Duty"});
                table1912.AddRow(new string[] {
                            "Billy",
                            "Bob",
                            "yes",
                            "52000",
                            "Operations or Cashier"});
#line 39
 testRunner.Then("user handles the WC Covered OO with these values:", ((string)(null)), table1912, "Then ");
#line hidden
#line 42
 testRunner.Then("user continues on from the WC OO page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
 testRunner.Then("user verifies the appearance of the WC Your Services Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1913 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1913.AddRow(new string[] {
                            "Do you use pyrotechnics?",
                            "no"});
                table1913.AddRow(new string[] {
                            "Do you perform acts with knives, other sharp objects, fire, or live ammunition?",
                            "no"});
                table1913.AddRow(new string[] {
                            "Do you do any work higher than 30 feet above ground?",
                            "no"});
                table1913.AddRow(new string[] {
                            "Do you help set up furniture or install any sound/lighting at events?",
                            "no"});
                table1913.AddRow(new string[] {
                            "In the past 3 years how many Workers\' Compensation claims were reported?",
                            "None"});
                table1913.AddRow(new string[] {
                            "Do you work with lions, tigers, leopards, bears, elephants, or venomous reptiles?" +
                                "",
                            "no"});
                table1913.AddRow(new string[] {
                            "Do you currently have a Workers\' Compensation insurance policy in effect?",
                            "yes"});
                table1913.AddRow(new string[] {
                            "Do you use any volunteers or donated labor?",
                            "yes"});
                table1913.AddRow(new string[] {
                            "What percentage of workers are volunteers or donated labor?",
                            "40"});
                table1913.AddRow(new string[] {
                            "Were you looking to buy insurance, in case of an injury, for your volunteers?",
                            "Yes"});
                table1913.AddRow(new string[] {
                            "Do you have multiple locations in more than one state?",
                            "no"});
#line 44
 testRunner.Then("user fills out the WC Your Services page", ((string)(null)), table1913, "Then ");
#line hidden
#line 57
 testRunner.Then("user verifies the WC decline page appearance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
