// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BiBerkLOB.Features.PL.Issued.ServiceIndustries_Issued
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PL_EmailYourQuoteFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "PL_EmailYourQuote.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/PL/Issued/ServiceIndustries_Issued", "PL_EmailYourQuote", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PL_EmailYourQuote")))
            {
                global::BiBerkLOB.Features.PL.Issued.ServiceIndustries_Issued.PL_EmailYourQuoteFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("PL Graphic Design: No sign Installation Purchase for Missouri (Email your quote m" +
            "odal)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PL_EmailYourQuote")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PL")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Test")]
        public void PLGraphicDesignNoSignInstallationPurchaseForMissouriEmailYourQuoteModal()
        {
            string[] tagsOfScenario = new string[] {
                    "PL",
                    "Test"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PL Graphic Design: No sign Installation Purchase for Missouri (Email your quote m" +
                    "odal)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1055 = new TechTalk.SpecFlow.Table(new string[] {
                            "Industry",
                            "Employees",
                            "Location",
                            "Own or Lease",
                            "ZIP Code",
                            "LOB"});
                table1055.AddRow(new string[] {
                            "Graphic Designers: No Sign Installation",
                            "2",
                            "I Run My Business From Property I Own",
                            "",
                            "65781",
                            "PL"});
#line 5
 testRunner.Given("user starts a quote with:", ((string)(null)), table1055, "Given ");
#line hidden
#line 8
 testRunner.Then("user verifies the appearance of the PL A Quick Introduction page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1056 = new TechTalk.SpecFlow.Table(new string[] {
                            "Business Structure",
                            "Name of Business",
                            "DBA"});
                table1056.AddRow(new string[] {
                            "Corporation",
                            "Mikes Graphics",
                            "MGD"});
#line 9
 testRunner.Then("user fills out A Quick Introduction page with these values:", ((string)(null)), table1056, "Then ");
#line hidden
#line 12
 testRunner.Then("user verifies the appearance of the PL Business Details page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1057 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1057.AddRow(new string[] {
                            "What year was your business started?",
                            "2000"});
                table1057.AddRow(new string[] {
                            "What is your estimated gross annual revenue?",
                            "250,000"});
                table1057.AddRow(new string[] {
                            "Do you use a written contract or statement of work (SOW)?",
                            "Never"});
#line 13
 testRunner.Then("user fills out the PL Business Details page with these values:", ((string)(null)), table1057, "Then ");
#line hidden
#line 18
 testRunner.Then("user verifies the appearance of the PL Coverage Details page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1058 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1058.AddRow(new string[] {
                            "When should your policy start?",
                            ""});
                table1058.AddRow(new string[] {
                            "Do you currently have a Professional Liability (E&O) policy in effect?",
                            "No"});
                table1058.AddRow(new string[] {
                            "Have you had a Professional Liability (E&O) policy in the last 3 years?",
                            "No"});
#line 19
 testRunner.Then("user fills out the PL Coverage Details page with these values:", ((string)(null)), table1058, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1059 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1059.AddRow(new string[] {
                            "Do you have a written procedure to check materials for copyright or trademark vio" +
                                "lations?",
                            "No"});
                table1059.AddRow(new string[] {
                            "In the past 3 years, has any party threatened or made claims for damages or other" +
                                " legal remedies against you or against any business entity with which you or any" +
                                " other business owner have been associated as owner, principal, officer, or empl" +
                                "oyee?",
                            "No"});
#line 24
 testRunner.Then("user fills out the PL Your Services page", ((string)(null)), table1059, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1060 = new TechTalk.SpecFlow.Table(new string[] {
                            "Question",
                            "Answer"});
                table1060.AddRow(new string[] {
                            "First Name",
                            "Mike"});
                table1060.AddRow(new string[] {
                            "Last Name",
                            "Jones"});
                table1060.AddRow(new string[] {
                            "Address",
                            "109 Long Dr"});
                table1060.AddRow(new string[] {
                            "City",
                            "Willard"});
                table1060.AddRow(new string[] {
                            "Use as Mailing Address",
                            "Yes"});
                table1060.AddRow(new string[] {
                            "Email",
                            "MikeJones@yahoo.com"});
                table1060.AddRow(new string[] {
                            "Business Phone",
                            "7777777777"});
                table1060.AddRow(new string[] {
                            "Ext",
                            "7777"});
                table1060.AddRow(new string[] {
                            "Website/Social",
                            "www.MikeJones.com"});
#line 28
 testRunner.Then("user fills out About You page with these values:", ((string)(null)), table1060, "Then ");
#line hidden
#line 39
 testRunner.Then("user verifies the appearance of the PL Summary page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
 testRunner.Then("user verifies the PL Email Your Quote modal appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
 testRunner.Then("user selects their Yearly - Standard Quote", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table1061 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1061.AddRow(new string[] {
                            "Autopay",
                            "On"});
                table1061.AddRow(new string[] {
                            "CC Name",
                            "Mike Jones"});
                table1061.AddRow(new string[] {
                            "CC Number",
                            "4111 1111 1111 1111"});
                table1061.AddRow(new string[] {
                            "CC Expiration",
                            "07/25"});
                table1061.AddRow(new string[] {
                            "Street Address",
                            "1101 Fort Street Mall"});
                table1061.AddRow(new string[] {
                            "ZIP Code",
                            "96813"});
                table1061.AddRow(new string[] {
                            "City",
                            "Honolulu"});
                table1061.AddRow(new string[] {
                            "Phone",
                            "777-777-7777"});
                table1061.AddRow(new string[] {
                            "Extension",
                            ""});
#line 42
 testRunner.When("user fills out the PL purchase page with these values:", ((string)(null)), table1061, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
